name: Add a new GitHub issue to a designate project column
on: issues
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: add-new-issues-to-project-column
      uses: takanabe/add-new-issues-to-project-column@v0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/takanabe/add-new-issues-to-project-column/projects/1
        GITHUB_PROJECT_COLUMN_NAME: To do
